# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb8ae0a515e4e0e5440adde400255eb057fa6cebd31bd9d2c298fdc934275b46a8066d06cf7a1829ecf0a41d203a86714ceb190aa5976e94d295741824b0f128

test:
  secret_key_base: 9558859c362ad5da71b3cb4d36495fa2ce9d1fd7139c56cffd5d2398e7ebc2c7dd448f1418c7aebc9eb9a98bcd049d0156635211f855a1b5c97ec71bcb3b3125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
